# https://github.com/ulisesbocchio/jasypt-spring-boot
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD} # *Required*
    algorithm: PBEWITHMD5ANDDES # PBEWITHHMACSHA512ANDAES_256
#    key-obtention-iterations: 1000
#    pool-size: 1
#    provider-name: SunJCE
#    provider-class-name: null
#    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator # org.jasypt.iv.RandomIvGenerator
#    string-output-type: base64
#    proxy-property-sources: false
#    skip-property-sources:
#      - empty list