jwt:
  key:
    header: "Authorization"
    access-token: "accessToken"
    refresh-token: "refreshToken"
  algorithm: HS256
  secret: "kt ds 2023 Welcome Project - DSquare"
  expiration-millisecond: 60000
  prefix: "Bearer "
#  claims:
#    username: username
