### Spring Configuration ###
spring:
  ### Datasource ###
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dsquare
    username: postgres
    password: 1234

  ### Spring Data JPA ###
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true


  main:
    allow-bean-definition-overriding: true