### Server Configuration ###
server:
  port: 8090

### Spring Configuration ###
spring:
  ### Datasource ###
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5532/dsquare
    username: postgres
    password: new1234!

### Spring Data JPA ###
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

  ### Servlet ###
  servlet:
    multipart:
      max-file-size: 10MB

  ### Spring MVC ###
  mvc:
    # Config for Swagger
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

### Logging Configuration ###
logging:
  ### Level ###
  level:
    root: info
    org.hibernate:
      type:
        descriptor:
          sql: trace

    com.ktds.dsquare:
      auth.jwt: debug
      common.file: debug
