### Server Configuration ###
server:
  port: 8080

### Spring Configuration ###
spring:
  ### Datasource ###
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(jhgEOjHFuO/GAtoGbOfmGut4kP9n4ePZCoNY/0a7WQ8UpGUVS5nufIMB/kDMNdR/0nJneuz3600=)
    username: ENC(PU3Qll0ypMDtLlbPTSk6eA==)
    password: ENC(Bso4+im3uyF56XDNQslggQ==)

  ### Spring Data JPA ###
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
    show-sql: true

  ### Servlet ###
  servlet:
    multipart:
      max-file-size: 10MB

  ### Spring MVC ###
  mvc:
    # Config for Swagger
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

### Logging Configuration ###
logging:
  ### Level ###
  level:
    root: info
    com.ktds.dsquare:
      auth.jwt: debug
      common.file: debug
